use_frameworks!

target 'SDDropdown_Example' do
  pod 'SDDropdown', :path => '../'

  target 'SDDropdown_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
